apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livesync-bridge.fullname" . }}-scripts
  labels:
    {{- include "livesync-bridge.labels" . | nindent 4 }}
data:
  git-askpass.sh: |
    #!/bin/sh
    echo "$GITHUB_TOKEN"
  commit.sh: |
{{ .Files.Get "files/commit.sh" | indent 4 }}
